# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8315ea9f7758fff3f66514c983c9c9a50ff0c47e155bbe6c93245b5a8e1e19d29059478ddd6f897e2e3559803c976fd2becb00c300c583fc016e6db406a9d7c9

test:
  secret_key_base: 570b6fdc7d7bb9b7f5067b6b90a0b3512d4ec6dc38f9c342026f376382df90733fc9788c516bb98a65f691be52602c1aa66ce635d1bcc4b00788a74015565b80

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
